Add "type": "module" to hello-wasm-pack package.json
(Again no change in git, just manually edited
node_modules/hello-wasm-pack/package.json to add `"type": "module"`)

Output of `yarn dev`:

```
yarn run v1.22.11
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
error - Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/hello_wasm_pack.js
require() of ES modules is not supported.
require() of /Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/hello_wasm_pack.js from /Users/gthb/git/next-tries-to-do-wasm/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename hello_wasm_pack.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.hello-wasm-pack (/Users/gthb/git/next-tries-to-do-wasm/.next/server/pages/index.js:86:18)
    at __webpack_require__ (/Users/gthb/git/next-tries-to-do-wasm/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:11:73)
    at Object../pages/index.js (/Users/gthb/git/next-tries-to-do-wasm/.next/server/pages/index.js:55:1)
    at __webpack_require__ (/Users/gthb/git/next-tries-to-do-wasm/.next/server/webpack-runtime.js:33:42) {
  code: 'ERR_REQUIRE_ESM',
  page: '/'
}
```

Error shown in browser:

```
1 of 1 unhandled error
Server Error

Error: Must use import to load ES Module: /Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/hello_wasm_pack.js
require() of ES modules is not supported.
require() of /Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/hello_wasm_pack.js from /Users/gthb/git/next-tries-to-do-wasm/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename hello_wasm_pack.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/package.json.
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.Module._extensions..js
internal/modules/cjs/loader.js (1089:13)
Module.load
internal/modules/cjs/loader.js (937:32)
Function.Module._load
internal/modules/cjs/loader.js (778:12)
Module.require
internal/modules/cjs/loader.js (961:19)
require
internal/modules/cjs/helpers.js (92:18)
Object.hello-wasm-pack
file:/Users/gthb/git/next-tries-to-do-wasm/.next/server/pages/index.js (86:18)
__webpack_require__
file:/Users/gthb/git/next-tries-to-do-wasm/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./pages/index.js (11:73)
Object../pages/index.js
file:/Users/gthb/git/next-tries-to-do-wasm/.next/server/pages/index.js (55:1)
__webpack_require__
file:/Users/gthb/git/next-tries-to-do-wasm/.next/server/webpack-runtime.js (33:42)
```