enable experimental.esmExternals
Attempt to resolve that last error by telling Next to import the ESM module as an ESM module

Output of `yarn dev`:

```
yarn run v1.22.11
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
warn  - You have enabled experimental feature(s).
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use them at your own risk.

event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
Failed to parse source map: TypeError: Cannot read property 'line' of undefined
    at Object.getNotFoundError (/Users/gthb/git/next-tries-to-do-wasm/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js:69:29)
    at Object.getModuleBuildError (/Users/gthb/git/next-tries-to-do-wasm/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js:74:58)
    at /Users/gthb/git/next-tries-to-do-wasm/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:14:80
    at Array.map (<anonymous>)
    at /Users/gthb/git/next-tries-to-do-wasm/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js:12:79
    at Hook.eval [as callAsync] (eval at create (/Users/gthb/git/next-tries-to-do-wasm/node_modules/next/dist/compiled/webpack/bundle5.js:33832:10), <anonymous>:8:17)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/gthb/git/next-tries-to-do-wasm/node_modules/next/dist/compiled/webpack/bundle5.js:33634:14)
    at /Users/gthb/git/next-tries-to-do-wasm/node_modules/next/dist/compiled/webpack/bundle5.js:45256:38
    at eval (eval at create (/Users/gthb/git/next-tries-to-do-wasm/node_modules/next/dist/compiled/webpack/bundle5.js:33832:10), <anonymous>:15:1)
    at Hook.eval [as callAsync] (eval at create (/Users/gthb/git/next-tries-to-do-wasm/node_modules/next/dist/compiled/webpack/bundle5.js:33832:10), <anonymous>:6:1)
error - ./node_modules/hello-wasm-pack/hello_wasm_pack_bg.wasm
Module not found: Can't resolve './hello_wasm_pack' in '/Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack'
Did you mean 'hello_wasm_pack.js'?
BREAKING CHANGE: The request './hello_wasm_pack' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
error - unhandledRejection: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/hello_wasm_pack_bg' imported from /Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/hello_wasm_pack.js
    at finalizeResolution (internal/modules/esm/resolve.js:285:11)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
error - Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/hello_wasm_pack_bg' imported from /Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/hello_wasm_pack.js
    at finalizeResolution (internal/modules/esm/resolve.js:285:11)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36) {
  code: 'ERR_MODULE_NOT_FOUND',
  page: '/'
}
```