Delete the .next directory
(No change in git, just `rm -rf .next` locally, as suggested in
https://stackoverflow.com/questions/67652612/chunkloaderror-loading-chunk-node-modules-next-dist-client-dev-noop-js-failed
for the problem "ChunkLoadError: Loading chunk node_modules_next_dist_client_dev_noop_js failed")

That made the first error go away, but the `Cannot use import statement outside a module` remains.

Output of `yarn dev`:

```
yarn run v1.22.11
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /next/dist/pages/_error
wait  - compiling...
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
error - /Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/hello_wasm_pack.js:2
import * as wasm from './hello_wasm_pack_bg';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.hello-wasm-pack (/Users/gthb/git/next-tries-to-do-wasm/.next/server/pages/index.js:86:18)
    at __webpack_require__ (/Users/gthb/git/next-tries-to-do-wasm/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.js:11:73) {
  page: '/'
}
```

Error shown in browser:

```
1 of 1 unhandled error
Server Error

SyntaxError: Cannot use import statement outside a module
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:/Users/gthb/git/next-tries-to-do-wasm/node_modules/hello-wasm-pack/hello_wasm_pack.js (2)
wrapSafe
internal/modules/cjs/loader.js (988:16)
Module._compile
internal/modules/cjs/loader.js (1036:27)
Object.Module._extensions..js
internal/modules/cjs/loader.js (1101:10)
Module.load
internal/modules/cjs/loader.js (937:32)
Function.Module._load
internal/modules/cjs/loader.js (778:12)
Module.require
internal/modules/cjs/loader.js (961:19)
require
internal/modules/cjs/helpers.js (92:18)
Object.hello-wasm-pack
file:/Users/gthb/git/next-tries-to-do-wasm/.next/server/pages/index.js (86:18)
__webpack_require__
file:/Users/gthb/git/next-tries-to-do-wasm/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///./pages/index.js (11:73)
```